# Travis file for Anoncoin (anoncoind/anoncoin-qt)
# Documentation:
# - http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix
# - http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/
# Management & lint tool;
# - https://github.com/travis-ci/travis.rb#readme
matrix:
  include:
      - env: QTTYPE=4 USE_UPNP=- -DENABLE_WALLET=1 -DCMAKE_BUILD_TYPE=Release"
os:
 - linux
language:
 - cpp
compiler:
  - gcc
  - clang
cache:
  - apt
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe" # Boost 1.50
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.50-all-dev libdb++-dev libleveldb-dev libminiupnpc-dev libqrencode-dev libqt4-dev libssl-dev qt4-qmake
script:
  - cd i2psam
  - make -f makefile.unix
  - cd ../src
  - make -f makefile.unix
  - cd ..
  - qmake USE_UPNP=-
  - make
notifications:
  email:
    recipients:
      - meeh@sigterm.no
    on_success: change
    on_failure: change
  irc: 
    channels: 
      - "irc.freenode.net#anoncoin"
    template:
      - "%{repository}/%{branch} [linux] (%{commit} - %{author}): %{message}"
    on_failure: always
    on_success: change

---

os:
 - osx
language:
 - cpp
 - objective-c
include:
  - env: QTTYPE=4 USE_UPNP=- -DENABLE_WALLET=1 -DCMAKE_BUILD_TYPE=Release"
compiler:
  - clang
branches:
  only:
    - master
before_install:
  - brew doctor
  - brew install autoconf automake pkg-config berkeley-db4 boost miniupnpc openssl qt5
script:
  - cd i2psam
  - make -f makefile.unix
  - cd ../src
  - make -f makefile.osx
  - cd ..
  - qmake USE_UPNP=-
  - make
notifications:
  email:
    recipients:
      - meeh@sigterm.no
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net#anoncoin"
    template:
      - "%{repository}/%{branch} [osx] (%{commit} - %{author}): %{message}"
    on_failure: always
    on_success: change


